### ISSUE TITLE
Story 1

### ISSUE THREAD

**Issue by 2MLCMonkeys** [ericpowell3d/Monki#2]
As a fan of **[artist]**, I want to know everything about my [artist] so that I can be more obsessed.

# Tasks

- [x] create a search bar feature that accepts user input
- [x] get user input
- [x] api request for information
- [x] display in designated area artists information for the user
- [x] display showing dates for artist

**Comment by 2MLCMonkeys** [comment]
# User One

As a fan of [artist], I want to know everything about my [artist] so that I can be more obsessed.

# Tasks

- [ ] create a search bar feature that accepts user input
- [ ] get user input
- [ ] api request for information
- [ ] display in designated area artists information for the user
- [ ] display showing dates for artist

**Comment by novakjason** [comment]
## User Story
As a music lover, I want to know the up and coming tour dates and venues of my searched **[artist]** or artists near me so I can plan what concert to attend. 

## Acceptance Criteria
- [ ] Add a text input to capture user's desired location
- [ ] Use user's input to call API to generate map of desired location
- [ ] Display list of artists playing near location
